### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by jessicabarbalho** [telecapoland/jamendo-android#15]
I'm searching a way to develop the equalizer.

I've found this class: http://developer.android.com/reference/android/media/audiofx/Equalizer.html

I'm looking for a good solution because this one is only supported by Android 2.3 Gingerbread or up, it's only compatible with API 9 for Android.

What do you think? Have some suggestion? 

:)

**Comment by MarcinGil** [comment]
Looks good! Peek into the version fragmentation (http://developer.android.com/resources/dashboard/platform-versions.html) and see that Gingerbread is more than 60% and growing.

I think you can develop equalizer from this version up and check platform API runtime to enable it. No probs with that :)

**Comment by jessicabarbalho** [comment]
Nice, I started the development here https://github.com/jessicabarbalho/jamendo-android/tree/equalizer

I'm having some problems to manage the audio of the application, the examples of the Equalizer in the internet just show us how manage a specific audio file, in Jamendo's case there isn't audio's file because it is streaming, if you knew how I can configure the audio please tell me :)

I'm searching in the API how do it, thanks o/

**Comment by MarcinGil** [comment]
Hey,
I need a few days to check your solutions and dig in back to the code
as I haven't been doing anything there for some time. Project is
mostly unmaintained :).

On Thu, Jun 21, 2012 at 1:02 AM, jessicabarbalho
reply@reply.github.com
wrote:
