### ISSUE TITLE
[Equalizer] AudioEffect crashing on ICS and JB

### ISSUE THREAD

**Issue by dargad** [telecapoland/jamendo-android#24]
I experience major problems using Jamendo Android app on ICS and JB.

Starting one song works just fine, but when it switches to another one (either jumping to the next entry in the playlist or switched manually) the app crashes with:

```
09-08 20:20:14.335: E/AndroidRuntime(5704): java.lang.RuntimeException: AudioEffect: set/get parameter error
09-08 20:20:14.335: E/AndroidRuntime(5704):     at android.media.audiofx.AudioEffect.checkStatus(AudioEffect.java:1247)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at android.media.audiofx.Equalizer.getProperties(Equalizer.java:532)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at com.teleca.jamendo.media.PlayerEngineImpl.play(PlayerEngineImpl.java:223)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at com.teleca.jamendo.media.PlayerEngineImpl$3.onPrepared(PlayerEngineImpl.java:327)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:1975)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at android.os.Handler.dispatchMessage(Handler.java:99)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at android.os.Looper.loop(Looper.java:137)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at android.app.ActivityThread.main(ActivityThread.java:4930)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at java.lang.reflect.Method.invokeNative(Native Method)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at java.lang.reflect.Method.invoke(Method.java:511)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
09-08 20:20:14.335: E/AndroidRuntime(5704):     at dalvik.system.NativeStart.main(Native Method)
```

The crash happens in this line (PlayerEngineImpl.java:223):

```
newEqualizer.setProperties(equalizer.getProperties());
```

According to what's pointed out on [StackOverflow](http://stackoverflow.com/questions/11193239/using-audiosessionid-value-to-instantiate-audiofx-class) and on [code.google.com](http://code.google.com/p/android/issues/detail?id=33669) it's caused by a bug in ICS and (probably) JB.

Do you have any ideas how to fix this crash? 
So far I just commented out lines 218-228 in PlayerEngineImpl.java which simply disables the Equalizer. It may be used as a temporary workaround for ICS and JB, but dropping equalizer is surely not the final solution.

I have verified that this issue is reproducible on my Nexus S (with official ICS and Cyanogenmod 9 and 10) and Sony Xperia P.

**Comment by MarcinGil** [comment]
Hmm.. Don't have anything with ICS/JB - that's why it probably slipped through. So for now either we should disable it API level based or put a catch for that particular exception.
