### ISSUE TITLE
keeps crashing on Android 4.1.2 Build JZO54K

### ISSUE THREAD

**Issue by DaCon** [telecapoland/jamendo-android#29]
reproducible on Galaxy Nexus and N7 devices: install, open radio channel, starts playing, user skip forward using gesture or buttons -> App crashes.

Android 4.1.2 Build JZO54K

**Comment by MarcinGil** [comment]
In works. Should be fixed coming week.
10 lis 2012 19:05, "DaCon" notifications@github.com napisał(a):

**Comment by MarcinGil** [comment]
Please install newest version and test. Thanks!

**Comment by DaCon** [comment]
issue fixed. it works now. also you may want to reply to some posts on the Chrome Web Store regarding this issue.

Marcin, your private(?) email is visible inside your last post on github, may be easy to harvest now ...

Thanks a lot for this quick fix.

cheers, Dan

**Comment by MarcinGil** [comment]
Thanks! Email removed :)
