### ISSUE TITLE
Explicit invalid intent makes application access privileged resources

### ISSUE THREAD

**Issue by l3st4t** [telecapoland/jamendo-android#34]
Explicit intent that violates intent filter for activity IntentDistributorActivity makes the application access the network in Caller class while attempting to get a Jamendo remote file from Jamendo host.
Intent should be rejected before potentially causing security issues.

Explicit intent example
Action: PICK_ACTIVITY category: DEFAULT
URI: http://www.jamendo.com/fr/track/147517
Component: IntentDistributorActivity 
while intent filter defined in the Manifest specifies VIEW/DEFAULT as possible actions for activity IntentDistributorActivity
This intent makes the application attempt to connect with a remote host through execute method in class Caller. Part of the intent URI is also used in the call, making data coming from outside the application reach privileged method calls.

**Comment by MarcinGil** [comment]
Hi! As of January Jamendo has taken over code maintenance (see https://github.com/jamendo/jamendo-android) and application by Teleca will no longer be fixed/developed.
