### ISSUE TITLE
Service seems running in the background, even when I stop the app

### ISSUE THREAD

**Issue by ReyhanJB** [telecapoland/jamendo-android#38]
**What steps will reproduce the problem?**
Open the app. Go to Radio menu. Select a channel and start playing. Then switch to another application (Jamendo is going to background and keeps playing). After a while, remove Jamendo from the recent app (stop the app).

**What is the expected output? What do you see instead?**
I expect by removing the app from recent list, it stops. Although Jamendo stops playing the sound, I can still see Jamendo Player item on my notification bar. 

**Please provide any additional information below**
I checked the number of wakelocks before and after reproducing the issue. It seems that this issue causes the system to acquire a wakelock, which drastically drained the battery of my device.

**Comment by MarcinGil** [comment]
Hey, this app has not been maintained for a few years now, as Jamendo has created their own app - but feel free to fork it!
